### ISSUE TITLE
Fiz algo parecido

### ISSUE THREAD

**Issue by cristovao-trevisan** [Maulem/Manga-Checker#1]
Olá, só avisando que eu fiz algo parecido, só que pra mais que o mangalivre apenas :grinning:.
Só não é opensource (ainda), mas se quiser testar só entrar em https://mangarida.com
Por hora funciona nesses sites (testados, só que alguns parecidos ele detecta automático):

[mangameta.in](https://mangameta.in/)
[manhuaplus.com](https://manhuaplus.com/)
[mangagreat.com](https://mangagreat.com/)
[flamescans.org](https://flamescans.org/)
[immortalupdates.com](https://immortalupdates.com/)
[mangatx.com](https://mangatx.com/)
[mangacultivator.com](https://mangacultivator.com/)
[mangalivre.net](https://mangalivre.net/)
[read.kenjanomago.com](https://read.kenjanomago.com/)
[neoxscans.net](https://neoxscans.net/)
[www.asurascans.com](https://www.asurascans.com/)
[mangarockteam.com](https://mangarockteam.com/)
[mangatyrant.com](https://mangatyrant.com/)

**Comment by Maulem** [comment]
Pô mano, achei bem interessante. Só pra saber, vc testa o número de capítulos de qual jeito no mangalivre? Porque recentemente eles colocaram aquela resposta http diferente e tive que usar o openCV pra "burlar" isso. Se tiver algum jeito mais simples gostaria de saber para poder implementar.

**Comment by cristovao-trevisan** [comment]
Fazendo a requisição com http direto o cloudfare bloqueia mesmo. O jeito de burlar que eu usei foi com puppeteer usando [user-agent do google](https://developers.google.com/search/docs/advanced/crawling/overview-google-crawlers). Alguns sites funcionam só com user-agent do google, outros só com puppeteer, mas com os dois é quase certo que dá certo.

Fiz em node também (mais fácil de usar o puppeteer).

**Comment by cristovao-trevisan** [comment]
E eu não testo o número de capítulos somente, eu extraio a lista completa, aí consigo usar 1 requisição pra N usuários que leem o mesmo manga
